---
# create directories for bindmount
- name: create bindmount directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ bindmount_dir }}/promtail"
    - "{{ bindmount_dir }}/traefik"

# copy promtail config
- name: copy config for promtail
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ bindmount_dir }}/promtail/config.yml"

# check if dynamic_conf.yml already exists
- name: check if traefik config exists
  ansible.builtin.stat:
    path: "{{ bindmount_dir }}/traefik/dynamic_conf.yml"
  register: traefik_config_stat

# copy dynamic_conf.yml if not already existant
- name: copy config for traefik
  ansible.builtin.template:
    src: dynamic_conf.yml.j2
    dest: "{{ bindmount_dir }}/traefik/dynamic_conf.yml"
  when: not traefik_config_stat.stat.exists

# copy docker-compose.yml
- name: copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose-common.yml.j2
    dest: /home/user/docker-compose-common.yml

# create .env from variable
- name: create .env file
  ansible.builtin.copy:
    dest: /home/user/.env
    content: "{{ lookup('env', 'DOCKER_ENV') }}"

# run docker container
- name: start containers
  ansible.builtin.command: docker compose -f /home/user/docker-compose-common.yml up -d --remove-orphans
  when: 
    - ansible_virtualization_type != "docker"
...
